import { Context, h } from 'koishi'
import { Config } from '../config'
import type { ApiClient } from '../api/client'
import type { HealthResponse } from '../api/types'
import { aliasCommand, COMMAND_NAMES, commandDescription, primaryCommand } from './names'
import {
  resolveOutputModes,
  formatTimestamp,
  getTypstRenderer,
  buildTypstTheme,
  escapeTypstText,
  createTypstFailureOutput,
} from '../index'

function formatTextOutput(data: HealthResponse, label: string): string {
  return `${label} ${COMMAND_NAMES.health.emoji} 健康检查

📊 状态: ${data.status === 'healthy' ? '✅ 健康' : '❌ 异常'}
⏰ 时间戳: ${formatTimestamp(data.timestamp)}
⏱️ 运行时间: ${formatUptime(data.uptime)}`
}

function formatUptime(ms: number): string {
  const seconds = Math.floor(ms / 1000)
  const minutes = Math.floor(seconds / 60)
  const hours = Math.floor(minutes / 60)
  const days = Math.floor(hours / 24)
  
  if (days > 0) {
    return `${days}天 ${hours % 24}小时 ${minutes % 60}分钟`
  } else if (hours > 0) {
    return `${hours}小时 ${minutes % 60}分钟`
  } else if (minutes > 0) {
    return `${minutes}分钟 ${seconds % 60}秒`
  } else {
    return `${seconds}秒`
  }
}

function generateTypstCode(data: HealthResponse, theme: ReturnType<typeof buildTypstTheme>, label: string): string {
  const timestamp = new Date().toLocaleString('zh-CN')
  const statusEmoji = data.status === 'healthy' ? '✅' : '❌'
  const statusText = data.status === 'healthy' ? '健康' : '异常'

  return `#set page(
  width: 400pt,
  height: auto,
  margin: (x: 14pt, y: 14pt),
  fill: ${theme.pageBg}
)

#set text(
  font: ("${theme.fontFamily}", "Noto Color Emoji", "Noto Sans CJK SC", "Microsoft YaHei"),
  size: 11pt,
  fill: ${theme.textColor},
  lang: "zh"
)

#align(center)[
  #block(
    fill: ${theme.headerFill},
    stroke: 2pt + ${theme.headerStroke},
    radius: 6pt,
    inset: 10pt,
    width: 100%
  )[
    #text(size: 16pt, weight: "bold", fill: ${theme.headerText})[
      ${escapeTypstText(label)} ${COMMAND_NAMES.health.emoji} 健康检查
    ]
  ]
]

#v(8pt)

#block(
  fill: ${theme.panelFill},
  stroke: 1pt + ${theme.panelStroke},
  radius: 4pt,
  inset: 12pt,
  width: 100%
)[
  #table(
    columns: (auto, 1fr),
    stroke: none,
    row-gutter: 8pt,
    
    text(weight: "bold", fill: ${theme.sectionTitle})[📊 状态],
    [${statusEmoji} ${escapeTypstText(statusText)}],
    
    text(weight: "bold", fill: ${theme.sectionTitle})[⏰ 时间戳],
    [${escapeTypstText(formatTimestamp(data.timestamp))}],
    
    text(weight: "bold", fill: ${theme.sectionTitle})[⏱️ 运行时间],
    [${escapeTypstText(formatUptime(data.uptime))}],
  )
]

#v(8pt)

#align(center)[
  #text(size: 8pt, fill: ${theme.statsText})[
    Generated by serverinfo-rest-client · ${escapeTypstText(timestamp)}
  ]
]
`
}

export function registerHealthCommand(
  ctx: Context,
  cfg: Config,
  apiClient: ApiClient,
  logger: any,
  prefix: string,
  label: string
) {
  ctx.command(primaryCommand(prefix, COMMAND_NAMES.health), commandDescription(COMMAND_NAMES.health, '健康检查'))
    .alias(aliasCommand(prefix, COMMAND_NAMES.health))
    .option('mode', '-m <mode:string> 输出模式 (text/image)')
    .action(async ({ session, options }) => {
      try {
        const data = await apiClient.get<HealthResponse>('/health')
        const modes = resolveOutputModes(options.mode, cfg)

        const results: h[] = []

        for (const mode of modes) {
          if (mode === 'text') {
            results.push(h.text(formatTextOutput(data, label)))
          } else if (mode === 'typst-image') {
            try {
              const renderer = await getTypstRenderer(ctx, cfg, logger)
              const theme = buildTypstTheme(cfg)
              const typstCode = generateTypstCode(data, theme, label)
              const pngBuffer = await renderer.toPng(typstCode, cfg.typstRenderScale)
              results.push(h.image(pngBuffer, 'image/png'))
            } catch (err) {
              logger.warn(`Typst 渲染失败: ${err}`)
              const fallback = createTypstFailureOutput(err, cfg, modes, formatTextOutput(data, label))
              if (fallback) results.push(fallback)
            }
          }
        }

        if (cfg.quoteCommandReplies && session.messageId) {
          return h('', [h.quote(session.messageId), ...results])
        }
        return results
      } catch (error) {
        logger.error(`健康检查失败: ${error}`)
        return `❌ 健康检查失败: ${error.message}`
      }
    })
}
