#import "common.typ": *
#set page(width: 400pt, height: auto, margin: 14pt, fill: theme-color("page_bg"))
#set text(font: text-fonts, size: 11pt, fill: theme-color("text"), lang: "zh")

#header([#payload.label 🩺 健康检查])
#v(8pt)
#panel([
  #table(
    columns: (auto, 1fr),
    stroke: none,
    row-gutter: 8pt,
    field-label([📊 状态]), [#payload.status_emoji #payload.status_text],
    field-label([⏰ 时间戳]), [#payload.timestamp],
    field-label([⏱️ 运行时间]), [#payload.uptime],
  )
])
#v(8pt)
#footer([Generated by serverinfo-rest-client · #payload.generated_at])
