#import "common.typ": *
#set page(width: 380pt, height: auto, margin: 14pt, fill: theme-color("page_bg"))
#set text(font: text-fonts, size: 11pt, fill: theme-color("text"), lang: "zh")

#header([#payload.label 📋 玩家名列表 (#payload.count 人在线)])
#v(8pt)
#panel([
  #if payload.names.len() == 0 {
    align(center, [🌙 当前没有玩家在线])
  } else {
    for (index, name) in payload.names.enumerate() {
      grid(columns: (30pt, 1fr), [#(index + 1).], [👤 #name])
      if index + 1 < payload.names.len() { v(6pt) }
    }
  }
])
#v(8pt)
#footer([Generated by serverinfo-rest-client · #payload.generated_at])
