#import "common.typ": *
#set page(width: 350pt, height: auto, margin: (x: 14pt, y: 14pt), fill: page-fill)
#set text(font: text-fonts, size: 11pt, fill: theme-color("text"), lang: "zh")

#align(center)[
  #block(
    fill: theme-color("header_fill"),
    stroke: 2pt + theme-color("header_stroke"),
    radius: 6pt,
    inset: 10pt,
    width: 100%,
  )[
    #text(size: 16pt, weight: "bold", fill: theme-color("header_text"))[
      #payload.label 🔢 玩家数量
    ]
  ]
]

#v(8pt)

#block(
  fill: theme-color("panel_fill"),
  stroke: 1pt + theme-color("panel_stroke"),
  radius: 4pt,
  inset: 16pt,
  width: 100%,
)[
  #align(center)[
    #text(size: 32pt, weight: "bold", fill: theme-color("section_title"))[#payload.count]
    #v(4pt)
    #text(size: 12pt)[人在线]
  ]
]

#v(8pt)
#align(center)[
  #text(size: 8pt, fill: theme-color("stats_text"))[
    Generated by serverinfo-rest-client · #payload.generated_at
  ]
]
