#import "common.typ": *
#let page-width = if payload.count == 0 { 350pt } else { 380pt }
#let rows = if payload.names.len() == 0 {
  ()
} else {
  let cells = ()
  for (index, name) in payload.names.enumerate() {
    cells.push([#(index + 1).])
    cells.push([#name])
  }
  cells
}
#set page(width: page-width, height: auto, margin: (x: 14pt, y: 14pt), fill: page-fill)
#set text(font: text-fonts, size: 11pt, fill: theme-color("text"), lang: "zh")

#align(center)[
  #block(fill: theme-color("header_fill"), stroke: 2pt + theme-color("header_stroke"), radius: 6pt, inset: 10pt, width: 100%)[
    #text(size: 16pt, weight: "bold", fill: theme-color("header_text"))[
      #payload.label 📝 玩家名列表#if payload.count > 0 [ (#payload.count 人在线)]
    ]
  ]
]
#v(8pt)
#block(fill: theme-color("panel_fill"), stroke: 1pt + theme-color("panel_stroke"), radius: 4pt, inset: 12pt, width: 100%)[
  #if payload.count == 0 {
    align(center)[#text(size: 12pt)[当前没有玩家在线]]
  } else {
    table(columns: (auto, 1fr), stroke: none, row-gutter: 6pt, ..rows)
  }
]
#v(8pt)
#align(center)[
  #text(size: 8pt, fill: theme-color("stats_text"))[
    Generated by serverinfo-rest-client · #payload.generated_at
  ]
]
