#import "common.typ": *
#set page(width: 350pt, height: auto, margin: 14pt, fill: theme-color("page_bg"))
#set text(font: text-fonts, size: 11pt, fill: theme-color("text"), lang: "zh")

#header([#payload.label 🔢 玩家数量])
#v(8pt)
#panel(inset: 16pt)[
  #align(center)[
    #text(size: 32pt, weight: "bold", fill: theme-color("section_title"))[#payload.count]
    #v(4pt)
    #text(size: 12pt)[👥 人在线]
  ]
]
#v(8pt)
#footer([Generated by serverinfo-rest-client · #payload.generated_at])
