#import "common.typ": *
#set page(width: 400pt, height: auto, margin: (x: 14pt, y: 14pt), fill: page-fill)
#set text(font: text-fonts, size: 11pt, fill: theme-color("text"), lang: "zh")

#align(center)[
  #block(
    fill: theme-color("header_fill"),
    stroke: 2pt + theme-color("header_stroke"),
    radius: 6pt,
    inset: 10pt,
    width: 100%,
  )[
    #text(size: 16pt, weight: "bold", fill: theme-color("header_text"))[
      #payload.label 📊 服务器状态
    ]
  ]
]

#v(8pt)

#block(
  fill: theme-color("panel_fill"),
  stroke: 1pt + theme-color("panel_stroke"),
  radius: 4pt,
  inset: 12pt,
  width: 100%,
)[
  #table(
    columns: (auto, 1fr),
    stroke: none,
    row-gutter: 8pt,
    align: (left, horizon),
    text(weight: "bold", fill: theme-color("section_title"))[#payload.status_emoji 状态], [#payload.status],
    text(weight: "bold", fill: theme-color("section_title"))[🔌 服务端插件], [#payload.plugin v#payload.plugin_version],
    text(weight: "bold", fill: theme-color("section_title"))[🤖 Bot 客户端], [v#payload.client_version],
    text(weight: "bold", fill: theme-color("section_title"))[👥 在线玩家], [#payload.player_count],
    text(weight: "bold", fill: theme-color("section_title"))[🎮 BDS 版本], [#payload.bds_version],
    text(weight: "bold", fill: theme-color("section_title"))[📡 协议版本], [#payload.protocol_version],
  )
]

#v(8pt)
#align(center)[
  #text(size: 8pt, fill: theme-color("stats_text"))[
    Generated by serverinfo-rest-client · #payload.generated_at
  ]
]
