#import "common.typ": *
#set page(width: 400pt, height: auto, margin: 14pt, fill: theme-color("page_bg"))
#set text(font: text-fonts, size: 11pt, fill: theme-color("text"), lang: "zh")

#header([#payload.label 📊 服务器状态])
#v(8pt)
#panel([
  #table(
    columns: (auto, 1fr),
    stroke: none,
    row-gutter: 8pt,
    align: (left, horizon),
    field-label([#payload.status_emoji 状态]), [#payload.status],
    field-label([🔌 服务端插件]), [#payload.plugin v#payload.plugin_version],
    field-label([🤖 Bot 客户端]), [v#payload.client_version],
    field-label([👥 在线玩家]), [#payload.player_count],
    field-label([🎮 BDS 版本]), [#payload.bds_version],
    field-label([📡 协议版本]), [#payload.protocol_version],
  )
])
#v(8pt)
#footer([Generated by serverinfo-rest-client · #payload.generated_at])
